services:
    - docker

language: go

go:
  - 1.8

branches:
  only:
    - master

before_install:
  - curl https://glide.sh/get | sh
  - make deps

script:
  # check build a binary
  - make dev
  # run tests
  - make testv
