
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/Songmu/wrapcommander"

[[constraint]]
  branch = "master"
  name = "github.com/cjoudrey/gluahttp"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-getter"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  branch = "master"
  name = "github.com/kohkimakimoto/gluaenv"

[[constraint]]
  branch = "master"
  name = "github.com/kohkimakimoto/gluafs"

[[constraint]]
  branch = "master"
  name = "github.com/kohkimakimoto/gluaquestion"

[[constraint]]
  branch = "master"
  name = "github.com/kohkimakimoto/gluatemplate"

[[constraint]]
  branch = "master"
  name = "github.com/kohkimakimoto/gluayaml"

[[constraint]]
  name = "github.com/mattn/go-runewidth"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/otm/gluash"

[[constraint]]
  branch = "master"
  name = "github.com/yuin/gluare"

[[constraint]]
  branch = "master"
  name = "github.com/yuin/gopher-lua"

[[constraint]]
  branch = "master"
  name = "layeh.com/gopher-json"
